# Data Cleaning for Gender IDEAL

Before committing, please re-run the kernel with clear any output to avoid any merge issues with jupyter and github.

## Imports

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import altair as alt

ModuleNotFoundError: No module named 'altair'

## Reading in csvs

#### Summary about columns in Vision file

* There are 44 columns in Vision & Commitment. The multiple choice answers do not come downloaded with the question label. The answers are the column names and the first column name is the first option a user could choose.
* If a type of multiple choice response was already used in an earlier question, a number is appended to it, like None.1
* Tableau prefers data to be "tall and thin" (i.e. instead of one row per respondent, one row per question) https://www.tableau.com/about/blog/2018/2/prepare-survey-data-analysis-three-easy-steps-83122 -> This can be done in Tableau using the pivot functionality

### Vision
This includes the benchmark questions such as number of employees, number of years, industry, workforce type. 

Also includes "other relevant info" which is open response. Can we remove this?

In [14]:
vision = pd.read_csv("../data_original/24_vision_anon.csv")
del vision['Other.2']
del vision['Other.3']
#Drop the last column:
vision.drop(columns=df.columns[-1:],
           axis=1,
           inplace=True)
vision

,Organization,How many employees does your organization have?,For how many years has your organization been in operation?,What is your organization's industry?,Tell us about your organization's workforce?,"Thanks! You're done with the registration process. Before we jump into the assessment, can you tell us a few other things about your workplace (if relevant).","N/A, No EDI policy in place",Women and people who identify as women,Working mothers,"Women of color, including all races and ethnicities",...,"Yes, internal statement made to all employees","Yes, official public/external statement made about organization's commitment to gender equity","Vision & Commitment: Does your workplace publish an annual report on its performance on gender equity, diversity and inclusion that includes the following:",Womens Empowerment Principles (UN),HRC's Corporate Equality Index,LeanIn.org/McKinsey Workplace Survey,Paradigm for Parity,Gender Equality Index,None.3,"Vision & Commitment: Before we move to the next section, is there anything else you want to tell us about how your organization has articulated and reinforces its vision and commitment to gender equity?"
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"Offices in New York and Newark, NJ","N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,We employee veritable part time employees who ...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,The bulk of our employee base either works in ...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,Buckle is a startup company. Most employees ar...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,We are headquartered in NYC with satellite off...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,Prior to covid mostly DC based. Post covid pro...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,We have one contractor in India and a small te...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,It is pretty straight forward- exempt employee...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,We have a Women's slack channel that is open t...
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"Teams also in Canada, Singapore and UK","N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,Team is entirely based in NY,NaN,NaN,NaN,"Women of color, including all races and ethnic...",...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,Massachusetts-focused,NaN,Women and people who identify as women,NaN,NaN,...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"Liberia, Malawi, Ethiopia, Uganda. We did not ...","N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,US employees only,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,The CEO has mentioned to me (the only female i...
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,Not relevant,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,Publish an annual EDI report that includes per...,NaN,NaN,NaN,NaN,NaN,None,"We have a broader DEI policy, goals, etc. tha..."
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,No employees outside of the US. Not challengin...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,We have a predominantly female workforce - 70...
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,not relevant,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,All of our employees are in US. We are a mun...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,I am completing this from the perspective of o...
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,"We have employees in London, Dublin & Singapor...",NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,"We have women partners, etc that are members o..."
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,We have one hourly employee currently working ...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,"Yes, internal statement made to all employees","Yes, official public/external statement made a...",No EDI report is published,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,We reinforce our commitment to gender equity e...

In [9]:
df = vision.copy()
df

,Organization,How many employees does your organization have?,For how many years has your organization been in operation?,What is your organization's industry?,Tell us about your organization's workforce?,"Thanks! You're done with the registration process. Before we jump into the assessment, can you tell us a few other things about your workplace (if relevant).","N/A, No EDI policy in place",Women and people who identify as women,Working mothers,"Women of color, including all races and ethnicities",...,"Yes, internal statement made to all employees","Yes, official public/external statement made about organization's commitment to gender equity","Vision & Commitment: Does your workplace publish an annual report on its performance on gender equity, diversity and inclusion that includes the following:",Womens Empowerment Principles (UN),HRC's Corporate Equality Index,LeanIn.org/McKinsey Workplace Survey,Paradigm for Parity,Gender Equality Index,None.3,"Vision & Commitment: Before we move to the next section, is there anything else you want to tell us about how your organization has articulated and reinforces its vision and commitment to gender equity?"
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"Offices in New York and Newark, NJ","N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,We employee veritable part time employees who ...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,The bulk of our employee base either works in ...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,Buckle is a startup company. Most employees ar...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,We are headquartered in NYC with satellite off...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,Prior to covid mostly DC based. Post covid pro...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,We have one contractor in India and a small te...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,It is pretty straight forward- exempt employee...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,We have a Women's slack channel that is open t...
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"Teams also in Canada, Singapore and UK","N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,Team is entirely based in NY,NaN,NaN,NaN,"Women of color, including all races and ethnic...",...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,Massachusetts-focused,NaN,Women and people who identify as women,NaN,NaN,...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",...,NaN,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"Liberia, Malawi, Ethiopia, Uganda. We did not ...","N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,US employees only,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,"Yes, internal statement made to all employees",NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,The CEO has mentioned to me (the only female i...
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,Not relevant,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,Publish an annual EDI report that includes per...,NaN,NaN,NaN,NaN,NaN,None,"We have a broader DEI policy, goals, etc. tha..."
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,No employees outside of the US. Not challengin...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,We have a predominantly female workforce - 70...
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,not relevant,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,All of our employees are in US. We are a mun...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,I am completing this from the perspective of o...
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,"We have employees in London, Dublin & Singapor...",NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,NaN,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,None,"We have women partners, etc that are members o..."
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,We have one hourly employee currently working ...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,"Yes, internal statement made to all employees","Yes, official public/external statement made a...",No EDI report is published,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,We reinforce our commitment to gender equity e...

In [4]:
#Renaming some of the columns to be shorter
df.rename(columns={'How many employees does your organization have?':'number_of_employees','For how many years has your organization been in operation?':'number_of_years',"What is your organization's industry?":'industry',"Tell us about your organization's workforce?":"workforce"},inplace=True)
df

,Organization,number_of_employees,number_of_years,industry,workforce,"Thanks! You're done with the registration process. Before we jump into the assessment, can you tell us a few other things about your workplace (if relevant).","N/A, No EDI policy in place",Women and people who identify as women,Working mothers,"Women of color, including all races and ethnicities",...,"Vision & Commitment: Does your workplace publish an annual report on its performance on gender equity, diversity and inclusion that includes the following:",Other.2,Womens Empowerment Principles (UN),HRC's Corporate Equality Index,LeanIn.org/McKinsey Workplace Survey,Paradigm for Parity,Gender Equality Index,None.3,Other.3,"Vision & Commitment: Before we move to the next section, is there anything else you want to tell us about how your organization has articulated and reinforces its vision and commitment to gender equity?"
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN,NaN
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"Offices in New York and Newark, NJ","N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,We employee veritable part time employees who ...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,The bulk of our employee base either works in ...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN,NaN
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,Buckle is a startup company. Most employees ar...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,We are headquartered in NYC with satellite off...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,Prior to covid mostly DC based. Post covid pro...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,We have one contractor in India and a small te...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,It is pretty straight forward- exempt employee...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,We have a Women's slack channel that is open t...
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"Teams also in Canada, Singapore and UK","N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,Team is entirely based in NY,NaN,NaN,NaN,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,Massachusetts-focused,NaN,Women and people who identify as women,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"Liberia, Malawi, Ethiopia, Uganda. We did not ...","N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,US employees only,"N/A, No EDI policy in place",NaN,NaN,NaN,...,NaN,Internal report of demographic metrics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,NaN,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,The CEO has mentioned to me (the only female i...
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,Not relevant,"N/A, No EDI policy in place",NaN,NaN,NaN,...,Publish an annual EDI report that includes per...,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,"We have a broader DEI policy, goals, etc. tha..."
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,No employees outside of the US. Not challengin...,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,We have a predominantly female workforce - 70...
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,not relevant,"N/A, No EDI policy in place",NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,All of our employees are in US. We are a mun...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",...,NaN,"Prepare report on work on EDI, no gender perfo...",NaN,NaN,NaN,NaN,NaN,None,NaN,I am completing this from the perspective of o...
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,"We have employees in London, Dublin & Singapor...",NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,"We have women partners, etc that are members o..."
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,We have one hourly employee currently working ...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",...,No EDI report is published,NaN,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,Gender Equity Now,We reinforce our commitment to gender equity e...

In [5]:
df.columns

Index(['Organization', 'number_of_employees', 'number_of_years', 'industry',
       'workforce',
       'Thanks! You're done with the registration process.  Before we jump into the assessment, can you tell us a few other things about your workplace (if relevant).',
       'N/A, No EDI policy in place', 'Women and people who identify as women',
       'Working mothers',
       'Women of color, including all races and ethnicities',
       'Women of all types of abilities',
       'Persons of all non-binary gender identities',
       'Women of all sexual orientations', 'Women of all religions',
       'Women of all socio-economic levels',
       'Conducted a demographic analysis of the current workforce',
       'Conducted a baseline culture analysis using employee feedback to identify gaps',
       'Established goals regarding gender equity for the whole organization',
       'Developed a timebound roadmap to meet established goals', 'None',
       'Dedicated team responsible for establishing and tracking progress toward gender equity targets',
       'Specific timeline on when targets should be met',
       'Engagement with all staff on targets and their importance to the organization',
       'Training of all employees who have a direct impact on meeting targets',
       'None.1', 'Other', 'All Hiring Managers', 'Human Resources Dept',
       'All Senior Management', 'C-Suite', 'None.2', 'Other.1', 'No',
       'Yes, internal statement made to all employees',
       'Yes, official public/external statement made about organization's commitment to gender equity',
       'Vision & Commitment: Does your workplace publish an annual report on its performance on gender equity, diversity and inclusion that includes the following:',
       'Other.2', 'Womens Empowerment Principles (UN)',
       'HRC's Corporate Equality Index',
       'LeanIn.org/McKinsey Workplace Survey', 'Paradigm for Parity',
       'Gender Equality Index', 'None.3', 'Other.3',
       'Vision & Commitment: Before we move to the next section, is there anything else you want to tell us about how your organization has articulated and reinforces its vision and commitment to gender equity?'],
      dtype='object')

In [6]:
#Dropping some of the unneeded columns
df.drop(columns=["Thanks! You're done with the registration process.  Before we jump into the assessment, can you tell us a few other things about your workplace (if relevant).","Vision & Commitment: Before we move to the next section, is there anything else you want to tell us about how your organization has articulated and reinforces its vision and commitment to gender equity?"],inplace=True)
df

,Organization,number_of_employees,number_of_years,industry,workforce,"N/A, No EDI policy in place",Women and people who identify as women,Working mothers,"Women of color, including all races and ethnicities",Women of all types of abilities,...,"Yes, official public/external statement made about organization's commitment to gender equity","Vision & Commitment: Does your workplace publish an annual report on its performance on gender equity, diversity and inclusion that includes the following:",Other.2,Womens Empowerment Principles (UN),HRC's Corporate Equality Index,LeanIn.org/McKinsey Workplace Survey,Paradigm for Parity,Gender Equality Index,None.3,Other.3
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,NaN,NaN,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,Internal report of demographic metrics,NaN,NaN,NaN,NaN,NaN,None,NaN
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,Publish an annual EDI report that includes per...,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,NaN,NaN,NaN,"Women of color, including all races and ethnic...",NaN,...,NaN,NaN,"Prepare report on work on EDI, no gender perfo...",NaN,NaN,NaN,NaN,NaN,None,NaN
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,Gender Equity Now

In [7]:
#Renaming some of the columns based on Question # followed by _ then A/B/C/etc if a multiple selection
#Question # is from the survey at: https://gender-ideal.org/the-assessment
#Prepending the original column label with this
df=df.rename(columns={"N/A, No EDI policy in place":"Q9_A","Women and people who identify as women":"Q9_B",
                   "Working mothers":"Q9_C","Women of color, including all races and ethnicities":"Q9_D",
                  "Women of all types of abilities":"Q9_E","Persons of all non-binary gender identities":"Q9_F",
                  "Women of all sexual orientations":"Q9_G","Women of all religions":"Q9_H",
                   "Women of all socio-economic levels":"Q9_I",
                   "Conducted a demographic analysis of the current workforce"
                   :"Q10_A","Conducted a baseline culture analysis using employee feedback to identify gaps":"Q10_B",
                  "Established goals regarding gender equity for the whole organization":"Q10_C",
                  "Developed a timebound roadmap to meet established goals":"Q10_D","None":"Q10_E",
                   "Dedicated team responsible for establishing and tracking progress toward gender equity targets":
                  "Q11_A","Specific timeline on when targets should be met":"Q11_B",
                   "Engagement with all staff on targets and their importance to the organization":"Q11_C",
                  "Training of all employees who have a direct impact on meeting targets":"Q11_D",
                  "None.1":"Q11_E","Other":"Q11_F","All Hiring Managers":"Q12_A","Human Resources Dept":"Q12_B",
                  "All Senior Management":"Q12_C","C-Suite":"Q12_D","None.2":"Q12_E","Other.1":"Q12_F",
                  "No":"Q13_A","Yes, internal statement made to all employees":"Q13_B",
                  "Yes, official public/external statement made about organization's commitment to gender equity":
                  "Q13_C","Other.2":"Q14_Other",
                   "Vision & Commitment: Does your workplace publish an annual report on its performance on gender " +
                   "equity, diversity and inclusion that includes the following:":"Q14",
                   "Womens Empowerment Principles (UN)":"Q15_A","HRC's Corporate Equality Index":"Q15_B",
                  "LeanIn.org/McKinsey Workplace Survey":"Q15_C","Paradigm for Parity":"Q15_D","Gender Equality Index"
                  :"Q15_E","None.3":"Q15_F","Other.3":"Q15_G"})
df

,Organization,number_of_employees,number_of_years,industry,workforce,Q9_A,Q9_B,Q9_C,Q9_D,Q9_E,...,Q13_C,Q14,Q14_Other,Q15_A,Q15_B,Q15_C,Q15_D,Q15_E,Q15_F,Q15_G
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,NaN,NaN,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,Internal report of demographic metrics,NaN,NaN,NaN,NaN,NaN,None,NaN
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,Publish an annual EDI report that includes per...,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,NaN,NaN,NaN,"Women of color, including all races and ethnic...",NaN,...,NaN,NaN,"Prepare report on work on EDI, no gender perfo...",NaN,NaN,NaN,NaN,NaN,None,NaN
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,"Yes, official public/external statement made a...",No EDI report is published,NaN,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,Gender Equity Now

In [8]:
#Printing the renamed columns
df.columns

Index(['Organization', 'number_of_employees', 'number_of_years', 'industry',
       'workforce', 'Q9_A', 'Q9_B', 'Q9_C', 'Q9_D', 'Q9_E', 'Q9_F', 'Q9_G',
       'Q9_H', 'Q9_I', 'Q10_A', 'Q10_B', 'Q10_C', 'Q10_D', 'Q10_E', 'Q11_A',
       'Q11_B', 'Q11_C', 'Q11_D', 'Q11_E', 'Q11_F', 'Q12_A', 'Q12_B', 'Q12_C',
       'Q12_D', 'Q12_E', 'Q12_F', 'Q13_A', 'Q13_B', 'Q13_C', 'Q14',
       'Q14_Other', 'Q15_A', 'Q15_B', 'Q15_C', 'Q15_D', 'Q15_E', 'Q15_F',
       'Q15_G'],
      dtype='object')

In [9]:
#Printing the Organization name
df["Organization"]

0     Company 1X
1     Company 1W
2     Company 1V
3     Company 1U
4     Company 1T
5     Company 1S
6     Company 1R
7     Company 1Q
8     Company 1P
9     Company 1O
10    Company 1N
11    Company 1M
12    Company 1L
13    Company 1K
14    Company 1J
15    Company 1I
16    Company 1H
17    Company 1G
18    Company 1F
19    Company 1E
20    Company 1D
21    Company 1C
22    Company 1B
23    Company 1A
Name: Organization, dtype: object

In [10]:
#### Adding the benchmark column

#Groups are: Financial Services, Technology, General, Non-profit
# A, B, F, J, Q, U, V financial
# C, G, M, P General
# D, H, N, O, R, S, T, X Technology
# E, I, K, L, W Non-Profit

financial_group = ["Company 1A","Company 1B","Company 1F","Company 1J","Company 1Q","Company 1U","Company 1V"]
technology_group = ["Company 1D","Company 1H","Company 1N","Company 1O","Company 1R","Company 1S","Company 1T","Company 1X"]
nonprofit_group = ["Company 1E","Company 1I","Company 1K","Company 1L","Company 1W"]

#Creating new column to contain benchmark group info
df["benchmark_group"] = np.nan

#Resetting benchmark group for finance companies 
finance = df["Organization"].isin(financial_group)
df.loc[finance,"benchmark_group"] = "Finance"

#Resetting benchmark group for technology companies 
technology = df["Organization"].isin(technology_group)
df.loc[technology,"benchmark_group"] = "Technology"

#Resetting benchmark group for technology companies 
nonprofit = df["Organization"].isin(nonprofit_group)
df.loc[nonprofit,"benchmark_group"] = "NonProfit"


#Printing out the dataframe Organization and benchmark columns to double check
#Note that any companies in general will remain as Nan as these companies visualizations
#will not be shown with a benchmark filter
df[["Organization","benchmark_group"]]

   Organization benchmark_group
0    Company 1X      Technology
1    Company 1W       NonProfit
2    Company 1V         Finance
3    Company 1U         Finance
4    Company 1T      Technology
5    Company 1S      Technology
6    Company 1R      Technology
7    Company 1Q         Finance
8    Company 1P             NaN
9    Company 1O      Technology
10   Company 1N      Technology
11   Company 1M             NaN
12   Company 1L       NonProfit
13   Company 1K       NonProfit
14   Company 1J         Finance
15   Company 1I       NonProfit
16   Company 1H      Technology
17   Company 1G             NaN
18   Company 1F         Finance
19   Company 1E       NonProfit
20   Company 1D      Technology
21   Company 1C             NaN
22   Company 1B         Finance
23   Company 1A         Finance

In [11]:
#Notice how this column contains the single select responses but some rows contain NAN
df["Q14"]

0                            No EDI report is published
1                            No EDI report is published
2                            No EDI report is published
3                            No EDI report is published
4                            No EDI report is published
5                            No EDI report is published
6                            No EDI report is published
7                            No EDI report is published
8                            No EDI report is published
9                            No EDI report is published
10                           No EDI report is published
11                           No EDI report is published
12                           No EDI report is published
13                           No EDI report is published
14                           No EDI report is published
15                           No EDI report is published
16                                                  NaN
17                           No EDI report is published
18    Publish an annual EDI report that includes per...
19                           No EDI report is published
20                           No EDI report is published
21                                                  NaN
22                           No EDI report is published
23                           No EDI report is published
Name: Q14, dtype: object

In [12]:
#Notice how the other column contains the input responses
#The rows with these responses are the ones that are NaN above
#Typeform fills in NAN above if user selects other and puts the other input here
df["Q14_Other"]

0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
5                                                   NaN
6                                                   NaN
7                                                   NaN
8                                                   NaN
9                                                   NaN
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
14                                                  NaN
15                                                  NaN
16               Internal report of demographic metrics
17                                                  NaN
18                                                  NaN
19                                                  NaN
20                                                  NaN
21    Prepare report on work on EDI, no gender perfo...
22                                                  NaN
23                                                  NaN
Name: Q14_Other, dtype: object

In [13]:
#Addressing the NA other issue in Q14
#Relabeling the NAS in Q14 as string Other
df.loc[pd.notna(df["Q14_Other"]),"Q14"]="Other"
df["Q14"]

0                            No EDI report is published
1                            No EDI report is published
2                            No EDI report is published
3                            No EDI report is published
4                            No EDI report is published
5                            No EDI report is published
6                            No EDI report is published
7                            No EDI report is published
8                            No EDI report is published
9                            No EDI report is published
10                           No EDI report is published
11                           No EDI report is published
12                           No EDI report is published
13                           No EDI report is published
14                           No EDI report is published
15                           No EDI report is published
16                                                Other
17                           No EDI report is published
18    Publish an annual EDI report that includes per...
19                           No EDI report is published
20                           No EDI report is published
21                                                Other
22                           No EDI report is published
23                           No EDI report is published
Name: Q14, dtype: object

In [14]:
df

,Organization,number_of_employees,number_of_years,industry,workforce,Q9_A,Q9_B,Q9_C,Q9_D,Q9_E,...,Q14,Q14_Other,Q15_A,Q15_B,Q15_C,Q15_D,Q15_E,Q15_F,Q15_G,benchmark_group
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN,Technology
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN,Technology
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,Other,Internal report of demographic metrics,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,Publish an annual EDI report that includes per...,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,NaN,NaN,NaN,"Women of color, including all races and ethnic...",NaN,...,Other,"Prepare report on work on EDI, no gender perfo...",NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,No EDI report is published,NaN,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,Gender Equity Now,Finance

### Examining Each Question
#### Question 9

In [15]:
#Selecting all of the Q9 columns from the dataframe
#This is a choose all that apply question so each answer results in its own column
df[['Organization','Q9_A', 'Q9_B', 'Q9_C', 'Q9_D', 'Q9_E', 'Q9_F', 'Q9_G', 'Q9_H', 'Q9_I']]

,Organization,Q9_A,Q9_B,Q9_C,Q9_D,Q9_E,Q9_F,Q9_G,Q9_H,Q9_I
0,Company 1X,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Company 1W,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Company 1V,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Company 1U,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,Persons of all non-binary gender identities,Women of all sexual orientations,Women of all religions,Women of all socio-economic levels
4,Company 1T,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Company 1S,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,Persons of all non-binary gender identities,Women of all sexual orientations,Women of all religions,Women of all socio-economic levels
6,Company 1R,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Company 1Q,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,Persons of all non-binary gender identities,Women of all sexual orientations,Women of all religions,Women of all socio-economic levels
8,Company 1P,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Company 1O,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Company 1N,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Company 1M,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Company 1L,NaN,NaN,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,NaN,NaN,NaN,NaN
13,Company 1K,NaN,Women and people who identify as women,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Company 1J,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,Persons of all non-binary gender identities,Women of all sexual orientations,Women of all religions,NaN
15,Company 1I,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Company 1H,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Company 1G,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Company 1F,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Company 1E,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Company 1D,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Company 1C,NaN,NaN,NaN,"Women of color, including all races and ethnic...",NaN,NaN,NaN,NaN,NaN
22,Company 1B,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,Persons of all non-binary gender identities,Women of all sexual orientations,Women of all religions,Women of all socio-economic levels
23,Company 1A,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,Persons of all non-binary gender identities,Women of all sexual orientations,Women of all religions,Women of all socio-economic levels

It looks like there's at least one response per row, so no missing data in this question.

#### Question 10

In [16]:
#Selecting all of the Q10 columns from the dataframe
#This is a choose all that apply question so each answer results in its own column
df[['Organization','Q10_A', 'Q10_B', 'Q10_C', 'Q10_D', 'Q10_E']]

,Organization,Q10_A,Q10_B,Q10_C,Q10_D,Q10_E
0,Company 1X,Conducted a demographic analysis of the curren...,NaN,Established goals regarding gender equity for ...,NaN,NaN
1,Company 1W,NaN,NaN,NaN,NaN,None
2,Company 1V,NaN,NaN,Established goals regarding gender equity for ...,Developed a timebound roadmap to meet establis...,NaN
3,Company 1U,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN
4,Company 1T,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
5,Company 1S,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,Established goals regarding gender equity for ...,Developed a timebound roadmap to meet establis...,NaN
6,Company 1R,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN
7,Company 1Q,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
8,Company 1P,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN
9,Company 1O,NaN,NaN,Established goals regarding gender equity for ...,NaN,NaN
10,Company 1N,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN
11,Company 1M,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
12,Company 1L,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN
13,Company 1K,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN
14,Company 1J,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
15,Company 1I,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,Established goals regarding gender equity for ...,Developed a timebound roadmap to meet establis...,NaN
16,Company 1H,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,Established goals regarding gender equity for ...,NaN,NaN
17,Company 1G,NaN,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
18,Company 1F,NaN,NaN,NaN,NaN,None
19,Company 1E,NaN,NaN,Established goals regarding gender equity for ...,NaN,NaN
20,Company 1D,Conducted a demographic analysis of the curren...,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
21,Company 1C,NaN,Conducted a baseline culture analysis using em...,NaN,NaN,NaN
22,Company 1B,Conducted a demographic analysis of the curren...,NaN,Established goals regarding gender equity for ...,NaN,NaN
23,Company 1A,Conducted a demographic analysis of the curren...,NaN,NaN,NaN,NaN

It looks like there's at least one response per row, so no missing data.

#### Question 11

In [17]:
df[['Organization','Q11_A','Q11_B', 'Q11_C', 'Q11_D', 'Q11_E', 'Q11_F']]

,Organization,Q11_A,Q11_B,Q11_C,Q11_D,Q11_E,Q11_F
0,Company 1X,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN
1,Company 1W,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN
3,Company 1U,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,Dedicated team responsible for establishing an...,Specific timeline on when targets should be met,Engagement with all staff on targets and their...,Training of all employees who have a direct im...,NaN,NaN
6,Company 1R,NaN,NaN,NaN,NaN,NaN,NaN
7,Company 1Q,Dedicated team responsible for establishing an...,NaN,Engagement with all staff on targets and their...,NaN,NaN,NaN
8,Company 1P,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,NaN,NaN,NaN,NaN,None,NaN
11,Company 1M,Dedicated team responsible for establishing an...,NaN,Engagement with all staff on targets and their...,Training of all employees who have a direct im...,NaN,NaN
12,Company 1L,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,NaN,NaN,NaN,NaN,NaN,NaN
14,Company 1J,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN
15,Company 1I,NaN,Specific timeline on when targets should be met,Engagement with all staff on targets and their...,NaN,NaN,Hired an external DEI consultant to help evalu...
16,Company 1H,NaN,NaN,Engagement with all staff on targets and their...,NaN,NaN,NaN
17,Company 1G,NaN,NaN,NaN,NaN,NaN,Engagement with SOME staff on targets and thei...
18,Company 1F,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN
19,Company 1E,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN
20,Company 1D,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,NaN,NaN,Engagement with all staff on targets and their...,Training of all employees who have a direct im...,NaN,NaN
22,Company 1B,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN
23,Company 1A,NaN,NaN,Engagement with all staff on targets and their...,NaN,NaN,NaN

Company R & K did not answer this question, but there is a response for "None" in this question. Checking with Flory about whether I should recode this company's response to None or No Response.

In [18]:
# If I recode to "No Response", I'll add a new column Q11_G that contains the value "No Response"
df["Q11_G"] = np.nan
df.loc[df["Organization"].isin(["Company 1R","Company 1K"]),"Q11_G"] = "No Response"
df[['Organization','Q11_A', 'Q11_B', 'Q11_C','Q11_D', 'Q11_E', 'Q11_F',"Q11_G"]]

,Organization,Q11_A,Q11_B,Q11_C,Q11_D,Q11_E,Q11_F,Q11_G
0,Company 1X,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN,NaN
1,Company 1W,NaN,NaN,NaN,NaN,None,NaN,NaN
2,Company 1V,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN,NaN
3,Company 1U,NaN,NaN,NaN,NaN,None,NaN,NaN
4,Company 1T,NaN,NaN,NaN,NaN,None,NaN,NaN
5,Company 1S,Dedicated team responsible for establishing an...,Specific timeline on when targets should be met,Engagement with all staff on targets and their...,Training of all employees who have a direct im...,NaN,NaN,NaN
6,Company 1R,NaN,NaN,NaN,NaN,NaN,NaN,No Response
7,Company 1Q,Dedicated team responsible for establishing an...,NaN,Engagement with all staff on targets and their...,NaN,NaN,NaN,NaN
8,Company 1P,NaN,NaN,NaN,NaN,None,NaN,NaN
9,Company 1O,NaN,NaN,NaN,NaN,None,NaN,NaN
10,Company 1N,NaN,NaN,NaN,NaN,None,NaN,NaN
11,Company 1M,Dedicated team responsible for establishing an...,NaN,Engagement with all staff on targets and their...,Training of all employees who have a direct im...,NaN,NaN,NaN
12,Company 1L,NaN,NaN,NaN,NaN,None,NaN,NaN
13,Company 1K,NaN,NaN,NaN,NaN,NaN,NaN,No Response
14,Company 1J,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN,NaN
15,Company 1I,NaN,Specific timeline on when targets should be met,Engagement with all staff on targets and their...,NaN,NaN,Hired an external DEI consultant to help evalu...,NaN
16,Company 1H,NaN,NaN,Engagement with all staff on targets and their...,NaN,NaN,NaN,NaN
17,Company 1G,NaN,NaN,NaN,NaN,NaN,Engagement with SOME staff on targets and thei...,NaN
18,Company 1F,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN,NaN
19,Company 1E,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN,NaN
20,Company 1D,NaN,NaN,NaN,NaN,None,NaN,NaN
21,Company 1C,NaN,NaN,Engagement with all staff on targets and their...,Training of all employees who have a direct im...,NaN,NaN,NaN
22,Company 1B,Dedicated team responsible for establishing an...,NaN,NaN,NaN,NaN,NaN,NaN
23,Company 1A,NaN,NaN,Engagement with all staff on targets and their...,NaN,NaN,NaN,NaN

#### Question 12

In [19]:
df[['Organization','Q12_A', 'Q12_B', 'Q12_C','Q12_D', 'Q12_E', 'Q12_F']]

,Organization,Q12_A,Q12_B,Q12_C,Q12_D,Q12_E,Q12_F
0,Company 1X,NaN,NaN,NaN,NaN,None,NaN
1,Company 1W,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,NaN,NaN,NaN,NaN,None,NaN
3,Company 1U,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,NaN,NaN,NaN,NaN,None,NaN
6,Company 1R,NaN,NaN,NaN,NaN,None,NaN
7,Company 1Q,NaN,NaN,NaN,NaN,NaN,NaN
8,Company 1P,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,NaN,NaN,NaN,NaN,NaN,There are no goals or specific targets but we ...
11,Company 1M,NaN,NaN,NaN,NaN,None,NaN
12,Company 1L,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,NaN,NaN,NaN,NaN,None,NaN
14,Company 1J,NaN,NaN,NaN,NaN,None,NaN
15,Company 1I,All Hiring Managers,NaN,All Senior Management,C-Suite,NaN,NaN
16,Company 1H,NaN,NaN,NaN,NaN,None,NaN
17,Company 1G,NaN,NaN,NaN,NaN,None,NaN
18,Company 1F,NaN,NaN,NaN,NaN,None,NaN
19,Company 1E,NaN,Human Resources Dept,NaN,NaN,NaN,NaN
20,Company 1D,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,NaN,NaN,NaN,NaN,None,NaN
22,Company 1B,All Hiring Managers,Human Resources Dept,NaN,NaN,NaN,NaN
23,Company 1A,NaN,NaN,NaN,NaN,None,NaN

Company Q did not answer this question. Checking with Flory about whether I should recode this company's response to None or No Response.

In [20]:
# If I recode to "No Response", I'll add a new column Q12_G that contains the value "No Response"
df["Q12_G"] = np.nan
df.loc[df["Organization"]=="Company 1Q","Q12_G"] = "No Response"
df[['Organization','Q12_A', 'Q12_B', 'Q12_C','Q12_D', 'Q12_E', 'Q12_F',"Q12_G"]]

,Organization,Q12_A,Q12_B,Q12_C,Q12_D,Q12_E,Q12_F,Q12_G
0,Company 1X,NaN,NaN,NaN,NaN,None,NaN,NaN
1,Company 1W,NaN,NaN,NaN,NaN,None,NaN,NaN
2,Company 1V,NaN,NaN,NaN,NaN,None,NaN,NaN
3,Company 1U,NaN,NaN,NaN,NaN,None,NaN,NaN
4,Company 1T,NaN,NaN,NaN,NaN,None,NaN,NaN
5,Company 1S,NaN,NaN,NaN,NaN,None,NaN,NaN
6,Company 1R,NaN,NaN,NaN,NaN,None,NaN,NaN
7,Company 1Q,NaN,NaN,NaN,NaN,NaN,NaN,No Response
8,Company 1P,NaN,NaN,NaN,NaN,None,NaN,NaN
9,Company 1O,NaN,NaN,NaN,NaN,None,NaN,NaN
10,Company 1N,NaN,NaN,NaN,NaN,NaN,There are no goals or specific targets but we ...,NaN
11,Company 1M,NaN,NaN,NaN,NaN,None,NaN,NaN
12,Company 1L,NaN,NaN,NaN,NaN,None,NaN,NaN
13,Company 1K,NaN,NaN,NaN,NaN,None,NaN,NaN
14,Company 1J,NaN,NaN,NaN,NaN,None,NaN,NaN
15,Company 1I,All Hiring Managers,NaN,All Senior Management,C-Suite,NaN,NaN,NaN
16,Company 1H,NaN,NaN,NaN,NaN,None,NaN,NaN
17,Company 1G,NaN,NaN,NaN,NaN,None,NaN,NaN
18,Company 1F,NaN,NaN,NaN,NaN,None,NaN,NaN
19,Company 1E,NaN,Human Resources Dept,NaN,NaN,NaN,NaN,NaN
20,Company 1D,NaN,NaN,NaN,NaN,None,NaN,NaN
21,Company 1C,NaN,NaN,NaN,NaN,None,NaN,NaN
22,Company 1B,All Hiring Managers,Human Resources Dept,NaN,NaN,NaN,NaN,NaN
23,Company 1A,NaN,NaN,NaN,NaN,None,NaN,NaN

#### Question 13

In [21]:
df[['Organization','Q13_A', 'Q13_B', 'Q13_C']]

,Organization,Q13_A,Q13_B,Q13_C
0,Company 1X,No,NaN,NaN
1,Company 1W,NaN,"Yes, internal statement made to all employees",NaN
2,Company 1V,NaN,"Yes, internal statement made to all employees",NaN
3,Company 1U,No,NaN,NaN
4,Company 1T,NaN,"Yes, internal statement made to all employees",NaN
5,Company 1S,NaN,NaN,"Yes, official public/external statement made a..."
6,Company 1R,NaN,"Yes, internal statement made to all employees",NaN
7,Company 1Q,NaN,"Yes, internal statement made to all employees",NaN
8,Company 1P,No,NaN,NaN
9,Company 1O,NaN,NaN,"Yes, official public/external statement made a..."
10,Company 1N,No,NaN,NaN
11,Company 1M,No,NaN,NaN
12,Company 1L,No,NaN,NaN
13,Company 1K,NaN,NaN,"Yes, official public/external statement made a..."
14,Company 1J,NaN,NaN,"Yes, official public/external statement made a..."
15,Company 1I,NaN,"Yes, internal statement made to all employees",NaN
16,Company 1H,No,NaN,NaN
17,Company 1G,NaN,"Yes, internal statement made to all employees",NaN
18,Company 1F,No,NaN,NaN
19,Company 1E,No,NaN,NaN
20,Company 1D,No,NaN,NaN
21,Company 1C,No,NaN,NaN
22,Company 1B,No,NaN,NaN
23,Company 1A,NaN,"Yes, internal statement made to all employees","Yes, official public/external statement made a..."

All companies provided a response for this one.

#### Question 14

In [51]:
df[['Organization','Q14','Q14_Other']]

,Organization,Q14,Q14_Other
0,Company 1X,No EDI report is published,NaN
1,Company 1W,No EDI report is published,NaN
2,Company 1V,No EDI report is published,NaN
3,Company 1U,No EDI report is published,NaN
4,Company 1T,No EDI report is published,NaN
5,Company 1S,No EDI report is published,NaN
6,Company 1R,No EDI report is published,NaN
7,Company 1Q,No EDI report is published,NaN
8,Company 1P,No EDI report is published,NaN
9,Company 1O,No EDI report is published,NaN
10,Company 1N,No EDI report is published,NaN
11,Company 1M,No EDI report is published,NaN
12,Company 1L,No EDI report is published,NaN
13,Company 1K,No EDI report is published,NaN
14,Company 1J,No EDI report is published,NaN
15,Company 1I,No EDI report is published,NaN
16,Company 1H,Other,Internal report of demographic metrics
17,Company 1G,No EDI report is published,NaN
18,Company 1F,Publish an annual EDI report that includes per...,NaN
19,Company 1E,No EDI report is published,NaN
20,Company 1D,No EDI report is published,NaN
21,Company 1C,Other,"Prepare report on work on EDI, no gender perfo..."
22,Company 1B,No EDI report is published,NaN
23,Company 1A,No EDI report is published,NaN

All companies provided a response for this question.

#### Question 15

In [52]:
df[['Organization','Q15_A', 'Q15_B', 'Q15_C', 'Q15_D', 'Q15_E', 'Q15_F','Q15_G']]

,Organization,Q15_A,Q15_B,Q15_C,Q15_D,Q15_E,Q15_F,Q15_G
0,Company 1X,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN
1,Company 1W,NaN,NaN,NaN,NaN,NaN,None,NaN
2,Company 1V,NaN,NaN,NaN,NaN,NaN,None,NaN
3,Company 1U,NaN,NaN,NaN,NaN,NaN,None,NaN
4,Company 1T,NaN,NaN,NaN,NaN,NaN,None,NaN
5,Company 1S,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN
6,Company 1R,NaN,NaN,NaN,NaN,NaN,None,NaN
7,Company 1Q,NaN,NaN,NaN,NaN,NaN,None,NaN
8,Company 1P,NaN,NaN,NaN,NaN,NaN,None,NaN
9,Company 1O,NaN,NaN,NaN,NaN,NaN,None,NaN
10,Company 1N,NaN,NaN,NaN,NaN,NaN,None,NaN
11,Company 1M,NaN,NaN,NaN,NaN,NaN,None,NaN
12,Company 1L,NaN,NaN,NaN,NaN,NaN,None,NaN
13,Company 1K,NaN,NaN,NaN,NaN,NaN,None,NaN
14,Company 1J,NaN,NaN,NaN,NaN,NaN,None,NaN
15,Company 1I,NaN,NaN,NaN,NaN,NaN,None,NaN
16,Company 1H,NaN,NaN,NaN,NaN,NaN,None,NaN
17,Company 1G,NaN,NaN,NaN,NaN,NaN,None,NaN
18,Company 1F,NaN,NaN,NaN,NaN,NaN,None,NaN
19,Company 1E,NaN,NaN,NaN,NaN,NaN,None,NaN
20,Company 1D,NaN,NaN,NaN,NaN,NaN,None,NaN
21,Company 1C,NaN,NaN,NaN,NaN,NaN,None,NaN
22,Company 1B,NaN,NaN,NaN,NaN,NaN,None,NaN
23,Company 1A,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,Gender Equity Now

All companies provided a response for this question

## Write out to CSV

In [53]:
#Print df one more time to double check
df

,Organization,number_of_employees,number_of_years,industry,workforce,Q9_A,Q9_B,Q9_C,Q9_D,Q9_E,...,Q15_A,Q15_B,Q15_C,Q15_D,Q15_E,Q15_F,Q15_G,benchmark_group,Q11_G,Q12_G
0,Company 1X,"1000-4,999 Employees",5-14 years,54 - software/technology,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,HRC's Corporate Equality Index,NaN,NaN,NaN,NaN,NaN,Technology,NaN,NaN
1,Company 1W,Fewer than 100 Employees,15 or more years,non-profit,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit,NaN,NaN
2,Company 1V,Fewer than 100 Employees,5-14 years,52 - financial services,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance,NaN,NaN
3,Company 1U,Fewer than 100 Employees,15 or more years,52 (financial services and investing),At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance,NaN,NaN
4,Company 1T,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology,NaN,NaN
5,Company 1S,"1000-4,999 Employees",Fewer than 5 years,NaN,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,NaN,NaN,NaN,Gender Equality Index,NaN,NaN,Technology,NaN,NaN
6,Company 1R,Fewer than 100 Employees,Fewer than 5 years,52 (Insurance),At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology,No Response,NaN
7,Company 1Q,250-999 Employees,5-14 years,523930,At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance,NaN,No Response
8,Company 1P,100-249 Employees,5-14 years,511210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
9,Company 1O,Fewer than 100 Employees,Fewer than 5 years,524126,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology,NaN,NaN
10,Company 1N,Fewer than 100 Employees,Fewer than 5 years,Finance and Insurance,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology,NaN,NaN
11,Company 1M,Fewer than 100 Employees,15 or more years,541613,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
12,Company 1L,Fewer than 100 Employees,5-14 years,813410,We have a mixed workforce of hourly and salari...,NaN,NaN,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit,NaN,NaN
13,Company 1K,Fewer than 100 Employees,15 or more years,624110,At least 80% of employees are Salaried,NaN,Women and people who identify as women,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit,No Response,NaN
14,Company 1J,"1000-4,999 Employees",15 or more years,Financial Services,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,NaN,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance,NaN,NaN
15,Company 1I,Fewer than 100 Employees,5-14 years,813319 - Other Social Advocacy Organizations,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit,NaN,NaN
16,Company 1H,250-999 Employees,5-14 years,518210,We have a mixed workforce of hourly and salari...,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology,NaN,NaN
17,Company 1G,Fewer than 100 Employees,Fewer than 5 years,611699,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
18,Company 1F,Fewer than 100 Employees,Fewer than 5 years,523920,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance,NaN,NaN
19,Company 1E,Fewer than 100 Employees,5-14 years,61,At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NonProfit,NaN,NaN
20,Company 1D,Fewer than 100 Employees,5-14 years,"2,426,347",At least 80% of employees are Salaried,"N/A, No EDI policy in place",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Technology,NaN,NaN
21,Company 1C,Fewer than 100 Employees,Fewer than 5 years,236210,At least 80% of employees are Hourly,NaN,NaN,NaN,"Women of color, including all races and ethnic...",NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
22,Company 1B,100-249 Employees,15 or more years,Finance (private equity),At least 80% of employees are Salaried,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,NaN,NaN,NaN,NaN,NaN,None,NaN,Finance,NaN,NaN
23,Company 1A,Fewer than 100 Employees,5-14 years,523920,We have a mixed workforce of hourly and salari...,NaN,Women and people who identify as women,Working mothers,"Women of color, including all races and ethnic...",Women of all types of abilities,...,Womens Empowerment Principles (UN),NaN,NaN,NaN,NaN,NaN,Gender Equity Now,Finance,NaN,NaN

In [54]:
#Write out to csv
df.to_csv("vision_clean_final.csv")

## Overall Steps
1. Ran notebook code above to generate vision_clean file
2. Dragged file into Tableau
3. Selected all columns that began with "Q" and then selected pivot
4. Renamed the pivoted columns to questions and responses
5. Created a group of the questions for Q9_ questions. Renamed this group with label of Q9 question.
6.

TODO Before Combining:
1. Confirm cleaning approach
2. Confirm naming for vision and edit the name typos.

In [2]:
#Reading in clean csv in case I only want to run this code block
df = pd.read_csv("../vision_clean_final.csv")

# Set it to None to display all rows in the dataframe
pd.set_option('display.max_rows', None)

In [4]:
df[["Organization","benchmark_group"]]

   Organization benchmark_group
0    Company 1X      Technology
1    Company 1W       NonProfit
2    Company 1V         Finance
3    Company 1U         Finance
4    Company 1T      Technology
5    Company 1S      Technology
6    Company 1R      Technology
7    Company 1Q         Finance
8    Company 1P             NaN
9    Company 1O      Technology
10   Company 1N      Technology
11   Company 1M             NaN
12   Company 1L       NonProfit
13   Company 1K       NonProfit
14   Company 1J         Finance
15   Company 1I       NonProfit
16   Company 1H      Technology
17   Company 1G             NaN
18   Company 1F         Finance
19   Company 1E       NonProfit
20   Company 1D      Technology
21   Company 1C             NaN
22   Company 1B         Finance
23   Company 1A         Finance

In [17]:
# Set it to None to display all rows in the dataframe
pd.set_option('display.max_rows', None)

#Show me all of the rows for the company I want to visualize
#Cell > Toggle Scrolling off to see all rows
df[df["Organization"]=="Company 1X"].T

                                                                     0
Unnamed: 0                                                           0
Organization                                                Company 1X
number_of_employees                               1000-4,999 Employees
number_of_years                                             5-14 years
workforce                       At least 80% of employees are Salaried
Q9_A                                       N/A, No EDI policy in place
Q9_B                                                               NaN
Q9_C                                                               NaN
Q9_D                                                               NaN
Q9_E                                                               NaN
Q9_F                                                               NaN
Q9_G                                                               NaN
Q9_H                                                               NaN
Q9_I                                                               NaN
Q10_A                Conducted a demographic analysis of the curren...
Q10_B                                                              NaN
Q10_C                Established goals regarding gender equity for ...
Q10_D                                                              NaN
Q10_E                                                              NaN
Q11_A                Dedicated team responsible for establishing an...
Q11_B                                                              NaN
Q11_C                                                              NaN
Q11_D                                                              NaN
Q11_E                                                              NaN
Q11_F                                                              NaN
Q12_A                                                              NaN
Q12_B                                                              NaN
Q12_C                                                              NaN
Q12_D                                                              NaN
Q12_E                                                             None
Q12_F                                                              NaN
Q13_A                                                               No
Q13_B                                                              NaN
Q13_C                                                              NaN
Q14                                         No EDI report is published
Q14_Other                                                          NaN
Q15_A                                                              NaN
Q15_B                                   HRC's Corporate Equality Index
Q15_C                                                              NaN
Q15_D                                                              NaN
Q15_E                                                              NaN
Q15_F                                                              NaN
Q15_G                                                              NaN
benchmark_group                                             Technology
Q11_G                                                              NaN
Q12_G                                                              NaN